# Form implementation generated from reading ui file 'Radhey_UI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 366)
        MainWindow.setMaximumSize(QtCore.QSize(459, 366))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("HD-Side-Flare-Poll-Black-Screen-Design-1080p-Background-.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 210, 161, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("animation.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 250, 271, 61))
        self.textBrowser.setStyleSheet("border-color: rgb(0, 0, 255);\n"
"background-color: transparent;\n"
"font: 700 15pt \"Magneto\" ;\n"
"border: 2px double rgb(0, 0, 255);\n"
"color: rgb(170, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 320, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: 2px solid ;\n"
"background-color: rgb(170, 255, 255);\n"
"border-color: rgb(0, 0, 255);\n"
"text-color:rgb(0, 0, 255);\n"
"border-radius:5px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 320, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border: 2px solid ;\n"
"background-color: rgb(170, 255, 255);\n"
"border-color: rgb(0, 0, 255);\n"
"text-color:rgb(0, 0, 255);\n"
"border-radius:5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(52, 270, 60, 20))
        self.label_3.setStyleSheet("font: 700 11pt \"Magneto\" ;\n"
"font-color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"border:0px;")
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.textBrowser_2.setStyleSheet("border-color: rgb(0, 0, 255);\n"
"background-color: transparent;\n"
"font: 700 10pt \"Magneto\" ;\n"
"border: 2px double rgb(0, 0, 255);\n"
"color: rgb(170, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Radhey"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#00aaff;\">MRP</span></p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
